# Specify base image (node:16-alpine)
FROM node:16-alpine

# Working directory in the container
WORKDIR '/app'

# Copy the package.json file to the container working directory and install npm
COPY package.json .
RUN npm install

# Copy the rest of the files into the working directory of the container
COPY . .

# Command to start up a development server
CMD ["npm", "run", "start"]